//
// Shader_2 [JC - Diffuse + Specular] lighting
//
const char* VS1 =
"#version 330 \r\n"
""
"	in vec4 s_vPosition;"
"	in vec4 s_vNormal;"
""
"	uniform mat4 mP;"
"	uniform mat4 mV;"
"	uniform mat4 mM;"
"	uniform mat4 mRotations;"
""
"	uniform vec4 vLight;"
""
"	out vec3 fN;"
"	out vec3 fL;"
"	out vec3 fE;"
""
"	void main()"
"	{"
"		gl_Position = mP*mV*mM*s_vPosition;"
""
"		fN = (mRotations*s_vNormal).xyz;"
"		fL = (vLight).xyz;"
"		fE = (mV*mM*s_vPosition).xyz;"
"	}";

const char* FS1 =
"#version 330 \r\n"
""
"	in vec3 fN;"
"	in vec3 fL;"
"	in vec3 fE;"
""
"	out vec4 fColor;"
""
"	void main()	"
"	{"
"		vec3 N = normalize(fN);"
"		vec3 L = normalize(fL);"
""
"		vec3 E = normalize(-fE);"
"		vec3 H = normalize(L + E);"
""
"		float diffuse_intensity = max(dot(N, L), 0.0);"
"		vec4 diffuse_final = diffuse_intensity*vec4(0.4, 0.4, 0.4, 1.0);"
""
"		float spec_intensity = pow(max(dot(N, H), 0.0), 1600);"
"		vec4 spec_final = spec_intensity*vec4(0.5, 0.4, 0.6, 1.0);"
""
"		fColor = diffuse_final + spec_final;"
"	}";